"""GENERATED by tools/dcc_study/fit_map.py — do not edit by hand.

Median measured aEgo (m/s^2) as a function of DCC setpoint gap
(cruiseState.speed - vEgo, m/s) and vEgo (m/s). Columns are forced
monotone in gap so the inversion in dcc_map.py is single-valued.

Cells filled by flat extrapolation (below MIN_CELL=150):
  (-3.0 m/s gap, 8.0 m/s speed): 95 samples
  (-2.0 m/s gap, 8.0 m/s speed): 56 samples
  (-1.5 m/s gap, 8.0 m/s speed): 64 samples

"""
GAP_BPS = [-3.0, -2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5]
V_BPS = [8.0, 14.0, 20.0, 26.0, 33.0]
A_TABLE = [
  [-1.0039, -1.0039, -1.0167, -1.1682, -0.9683],  # gap -3.0 m/s
  [-0.8720, -0.8720, -0.8889, -0.8185, -0.8561],  # gap -2.0 m/s
  [-0.6980, -0.6980, -0.6683, -0.6825, -0.7204],  # gap -1.5 m/s
  [-0.4822, -0.4134, -0.4172, -0.4358, -0.4603],  # gap -1.0 m/s
  [-0.2855, -0.2406, -0.2564, -0.2807, -0.3311],  # gap -0.5 m/s
  [-0.0030, -0.0314, -0.0870, -0.1138, -0.1926],  # gap +0.0 m/s
  [+0.0629, +0.0609, +0.0359, +0.0135, +0.0006],  # gap +0.5 m/s
  [+0.2840, +0.2299, +0.1960, +0.1711, +0.1265],  # gap +1.0 m/s
  [+0.4334, +0.4589, +0.3827, +0.3522, +0.3174],  # gap +1.5 m/s
]
N_TABLE = [
  [ 95, 7688, 12750, 3233, 2210],  # gap -3.0 m/s
  [ 56, 6209, 8656, 4041, 973],  # gap -2.0 m/s
  [ 64, 5937, 8696, 3963, 529],  # gap -1.5 m/s
  [834, 21132, 38054, 9321, 2790],  # gap -1.0 m/s
  [6038, 70838, 125615, 40525, 13774],  # gap -0.5 m/s
  [37406, 102843, 153975, 60307, 20709],  # gap +0.0 m/s
  [33856, 168508, 394404, 258695, 237797],  # gap +0.5 m/s
  [8137, 74282, 191847, 93165, 70716],  # gap +1.0 m/s
  [1486, 20363, 67352, 28276, 11970],  # gap +1.5 m/s
]
