"""Fit a_expected = f(setpoint gap, vEgo) and emit the shipped table module.

Offline only — never imported by the car. Run after extract.py:
    $PY fit_map.py
"""
import argparse
import glob
import math
from pathlib import Path

import numpy as np

from common import EXTRACTED_DIR

# Dense, monotone region only. Above +1.5 m/s of gap the data is 1.2% of
# samples and non-monotone; the controller clamps there instead.
GAP_BPS = [-3.0, -2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5]
V_BPS = [8.0, 14.0, 20.0, 26.0, 33.0]
MIN_CELL = 150          # samples required before a cell is trusted
DEFAULT_OUT = Path(__file__).resolve().parents[2] / "bmw" / "dcc_map_table.py"


def monotonise(col):
  """Running maximum, carrying the previous value across NaN.

  The inversion must be single-valued: a_expected has to increase with gap.
  """
  out, run = [], None
  for x in col:
    if x is not None and not math.isnan(x):
      run = x if run is None else max(run, x)
    out.append(run if run is not None else float("nan"))
  return out


def _edges(bps, lo_pad, hi_pad):
  mids = [(a + b) / 2 for a, b in zip(bps, bps[1:])]
  return [bps[0] - lo_pad] + mids + [bps[-1] + hi_pad]


def fit(extracted_dir):
  gaps, accs, vs = [], [], []
  for fn in sorted(glob.glob(str(Path(extracted_dir) / "*.npz"))):
    d = np.load(fn)
    m = (d["cruiseEnabled"] > 0) & (d["gas"] == 0) & (d["brake"] == 0) & (d["vEgo"] > 3.0)
    if m.sum() < 200:
      continue
    gaps.append(d["setpoint"][m] - d["vEgo"][m])
    accs.append(d["aEgo"][m])
    vs.append(d["vEgo"][m])
  if not gaps:
    print("samples: 0 (no segments with >= 200 qualifying samples)")
    gap = np.array([])
    acc = np.array([])
    v = np.array([])
  else:
    gap = np.concatenate(gaps)
    acc = np.concatenate(accs)
    v = np.concatenate(vs)
    print(f"samples: {len(gap):,}")

  g_edge = _edges(GAP_BPS, 1.0, 0.5)
  v_edge = _edges(V_BPS, 5.0, 12.0)
  table = []
  counts = []  # Track raw sample counts before any filling
  for i in range(len(GAP_BPS)):
    row = []
    count_row = []
    for j in range(len(V_BPS)):
      s = (gap >= g_edge[i]) & (gap < g_edge[i + 1]) & \
          (v >= v_edge[j]) & (v < v_edge[j + 1])
      n_samples = s.sum()
      count_row.append(int(n_samples))
      row.append(float(np.median(acc[s])) if n_samples >= MIN_CELL else float("nan"))
    table.append(row)
    counts.append(count_row)

  # Flat-extrapolate (not interpolate) across speed to fill sparse cells at range edges,
  # then force monotone in gap. At edges, np.interp clamps to the nearest valid value.
  for i, row in enumerate(table):
    ok = [j for j, x in enumerate(row) if not math.isnan(x)]
    if len(ok) >= 2:
      table[i] = list(np.interp(V_BPS, [V_BPS[j] for j in ok], [row[j] for j in ok]))
  cols = [monotonise([table[i][j] for i in range(len(GAP_BPS))])
          for j in range(len(V_BPS))]
  return GAP_BPS, V_BPS, [[cols[j][i] for j in range(len(V_BPS))]
                          for i in range(len(GAP_BPS))], counts


def emit(path, gap_bps, v_bps, table, counts=None):
  # Assert every cell is finite
  for i, row in enumerate(table):
    for j, x in enumerate(row):
      if not math.isfinite(x):
        raise ValueError(f"NaN or Inf in A_TABLE at gap {gap_bps[i]}, v {v_bps[j]}")

  lines = [
    '"""GENERATED by tools/dcc_study/fit_map.py — do not edit by hand.',
    "",
    "Median measured aEgo (m/s^2) as a function of DCC setpoint gap",
    "(cruiseState.speed - vEgo, m/s) and vEgo (m/s). Columns are forced",
    "monotone in gap so the inversion in dcc_map.py is single-valued.",
    "",
  ]

  if counts:
    filled_cells = []
    for i, (g, count_row) in enumerate(zip(gap_bps, counts)):
      for j, (v, n) in enumerate(zip(v_bps, count_row)):
        if n < MIN_CELL:
          filled_cells.append(f"  ({g:+.1f} m/s gap, {v:.1f} m/s speed): {n} samples")
    if filled_cells:
      lines.append(f"Cells filled by flat extrapolation (below MIN_CELL={MIN_CELL}):")
      lines.extend(filled_cells)
    lines.append("")

  lines.extend([
    '"""',
    f"GAP_BPS = {list(gap_bps)!r}",
    f"V_BPS = {list(v_bps)!r}",
    "A_TABLE = [",
  ])
  for g, row in zip(gap_bps, table):
    cells = ", ".join(f"{x:+.4f}" for x in row)
    lines.append(f"  [{cells}],  # gap {g:+.1f} m/s")
  lines.append("]")

  if counts:
    lines.append("N_TABLE = [")
    for g, count_row in zip(gap_bps, counts):
      cells = ", ".join(f"{n:3d}" for n in count_row)
      lines.append(f"  [{cells}],  # gap {g:+.1f} m/s")
    lines.append("]")

  lines.append("")
  Path(path).write_text("\n".join(lines))


def main():
  p = argparse.ArgumentParser()
  p.add_argument("--extracted", default=EXTRACTED_DIR, type=Path)
  p.add_argument("--out", default=DEFAULT_OUT, type=Path)
  args = p.parse_args()
  gap_bps, v_bps, table, counts = fit(args.extracted)
  for j, vb in enumerate(v_bps):
    col = [table[i][j] for i in range(len(gap_bps))]
    print(f"  v={vb * 3.6:>5.0f} kph  a: {col[0]:+.3f} .. {col[-1]:+.3f}")
  emit(args.out, gap_bps, v_bps, table, counts)
  print(f"wrote {args.out}")


if __name__ == "__main__":
  main()
